[workspace]
authors = ["Alvaro Gaona <alvgaona@gmail.com>"]
channels = ["conda-forge"]
name = "solar-hotspot-detection"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13,<3.14"

[pypi-dependencies]
roboflow = ">=1.2.11, <2"
ultralytics = ">=8.3.241, <9"
gradio = ">=6.2.0, <7"
